#line 1 "yar_lexer.c"

#line 3 "yar_lexer.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

#ifdef yyget_lval
#define yyget_lval_ALREADY_DEFINED
#else
#define yyget_lval yyget_lval
#endif

#ifdef yyset_lval
#define yyset_lval_ALREADY_DEFINED
#else
#define yyset_lval yyset_lval
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */

#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C++ systems might need __STDC_LIMIT_MACROS defined before including
 * <stdint.h>, if you want the limit (max/min) macros for int types.
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 35
#define YY_END_OF_BUFFER 36
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[190] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       36,   19,   12,   20,   34,    7,   16,   34,   34,   34,
       19,   21,   23,   25,   19,   19,   11,    3,    6,    4,
        6,    5,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    9,   10,   10,    7,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        8,   15,   14,   19,   19,   12,    1,    0,   28,    0,
       18,   19,   24,   26,   22,   31,   29,   27,   19,   13,
       17,   17,   17,    3,    3,    3,    3,    1,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,

        3,    3,    3,    3,    3,    3,    3,    9,   10,    9,
        9,   10,    9,    1,    9,    9,    9,   10,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,   15,   19,   19,    1,    0,    0,
        2,   30,   32,   33,    3,    3,    3,    3,    3,    3,
        1,    3,    3,    2,    3,    3,    3,    3,    3,    3,
        9,    9,    9,    9,    9,    9,    1,    9,   10,    9,
        2,    9,   10,    9,    9,    9,    9,    9,    3,    3,
       10,    2,    9,    9,    3,    2,    9,    2,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    5,    1,    6,    7,    8,    1,    9,   10,   11,
       11,    1,    1,    1,    1,    1,    1,   12,   12,   12,
       12,   12,   12,   12,   12,   12,   12,    1,   13,   14,
       15,   16,    1,    1,   17,   17,   17,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   17,   17,   17,
        1,   18,    1,    1,   17,    1,   17,   17,   17,   17,

       17,   17,   17,   17,   17,   17,   17,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   17,   17,   17,
       17,   17,   19,   11,   20,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[21] =
    {   0,
        1,    2,    3,    2,    2,    2,    4,    4,    4,    4,
        4,    1,    4,    4,    4,    4,    1,    1,    4,    4
    } ;

static const flex_int16_t yy_base[211] =
    {   0,
        0,    0,   20,    0,    0,    0,   40,    0,  259,  258,
      260,  241,   59,  760,  760,  760,  760,   46,  242,  246,
       65,  242,  245,   53,   83,  101,  760,  119,   65,  760,
      760,  760,  228,   54,   58,  136,  227,  154,   62,   69,
       76,  172,  190,  226,  210,   84,    0,    0,  230,   71,
      227,  247,    0,   91,  228,  231,   88,   97,  265,    0,
        0,    0,  760,  221,  285,   91,   98,  103,  222,  227,
      760,    0,  227,  226,  760,  760,  760,  760,    0,  760,
        0,    0,  303,  110,  216,  321,  340,   99,  357,  108,
      376,  215,  393,    0,   90,  125,  214,  195,  175,  170,

        0,  168,    0,    0,    0,    0,    0,    0,    0,    0,
      411,  127,  430,  116,  447,  169,  466,  141,    0,  483,
      133,  174,  173,    0,    0,    0,    0,  141,    0,    0,
        0,    0,    0,    0,    0,    0,    0,  118,  130,  178,
      760,  760,  760,  760,    0,    0,    0,    0,  161,  500,
        0,  517,  536,  151,  149,    0,  147,  553,  146,  144,
        0,    0,    0,    0,    0,  570,  140,  587,  156,  606,
        0,    0,    0,    0,    0,  623,    0,    0,    0,  640,
      158,    0,    0,  659,  157,   73,  160,    0,  760,  679,
       67,  683,  687,  691,  695,  699,  703,  707,  711,  715,

      719,  723,  727,  731,  735,  739,  743,  747,  751,  755
    } ;

static const flex_int16_t yy_def[211] =
    {   0,
      189,    1,  189,    3,    1,    1,  189,    7,  190,  190,
      189,  191,  189,  189,  189,  189,  189,  189,  189,  192,
      189,  189,  189,  189,  189,  193,  189,  194,  189,  189,
      189,  189,  194,  194,  194,  195,  194,  194,  194,  194,
      194,  194,  189,  194,  189,  196,  196,  196,   45,   49,
       49,  197,   49,   45,   49,   49,   49,   45,  189,   49,
       49,  198,  189,  191,  199,  189,  189,  200,  189,  192,
      189,   21,  189,  189,  189,  189,  189,  189,   25,  189,
       64,   64,  199,   42,  194,  189,  201,  194,  202,  194,
      195,  194,  203,   38,  194,  194,  194,  194,  194,  194,

       42,  194,   84,   84,   84,   84,   86,   45,  196,   49,
      189,  196,  204,   49,  205,   49,  197,  206,   49,  207,
       45,   49,   49,   49,   49,   49,   49,   45,   49,   45,
       45,   45,   45,  111,  198,   64,   83,  189,  200,  200,
      189,  189,  189,  189,   84,   84,   84,   86,  194,  201,
       88,  202,  208,  194,  194,   91,  194,  203,  194,  194,
       45,   45,   45,  111,   49,  204,   49,  205,  209,  210,
       49,   49,  196,  117,   49,  207,   49,   49,  152,  208,
      209,  196,  168,  210,  180,  194,  184,   49,    0,  189,
      189,  189,  189,  189,  189,  189,  189,  189,  189,  189,

      189,  189,  189,  189,  189,  189,  189,  189,  189,  189
    } ;

static const flex_int16_t yy_nxt[781] =
    {   0,
       12,   13,   14,   15,   13,   16,   17,   18,   19,   20,
       15,   21,   22,   23,   15,   24,   25,   26,   27,   15,
       28,   29,   30,   31,   29,   32,   33,   34,   35,   36,
       37,   38,   39,   40,   37,   41,   42,   43,   44,   37,
       45,   46,   14,   47,   46,   48,   49,   50,   51,   52,
       53,   54,   55,   56,   53,   57,   58,   59,   60,   61,
       66,   77,   67,   66,   68,   64,   66,   64,   78,   66,
       88,   87,   89,   90,   97,   87,   72,   98,   73,   87,
       74,   64,   65,   64,   99,  112,   87,  114,  112,  115,
       87,  100,   66,   87,   79,   66,  126,   80,  159,   79,

       65,   81,  121,  127,  122,   81,  123,   87,  128,  138,
      151,  129,   81,  128,  138,  151,   87,   81,   83,   84,
      140,   84,  141,  155,   85,   87,   84,  167,  112,  138,
       84,  112,  167,  160,  138,   84,   86,   70,   70,   70,
       70,   70,   87,   70,  121,   92,  122,  140,  123,  141,
      173,  167,  128,   93,   84,  129,  167,  128,  139,  189,
      189,   87,  189,   87,   87,   94,   87,   95,   87,   96,
       84,   86,   84,  181,  180,  182,  179,  184,   87,  183,
      189,  178,  177,  101,  172,   87,  102,   87,  101,   86,
      103,  104,   87,  104,  105,  104,  106,  106,  106,  106,

      106,  103,  106,  106,  106,  106,  103,  107,  106,  106,
      108,  109,   87,  109,  109,  109,  110,  110,  110,  110,
      110,  108,  110,  110,  110,  110,  108,  111,  110,  110,
      110,   87,   87,   87,  144,  143,   71,  142,   65,  125,
      124,  110,  116,   87,   87,   87,  110,  113,  118,   70,
      118,  118,  118,   76,   75,   71,  119,   69,   65,  189,
       63,   63,  189,  189,  120,  130,  131,  189,  131,  132,
      131,  133,  133,  133,  133,  133,  130,  133,  133,  133,
      133,  130,  134,  133,  133,  136,  189,  189,  189,  136,
      189,  189,  189,  189,  189,  189,  136,  189,  189,  189,

      189,  136,  137,  136,  189,  189,  189,  136,  189,  189,
      189,  189,  189,  189,  136,  189,  189,  189,  189,  136,
      137,  145,   84,  189,   84,  146,   84,  147,  147,  147,
      147,  147,  145,  147,  147,  147,  147,  145,  148,  147,
      147,   85,  189,   85,   85,   85,  189,  189,  189,  189,
      189,  189,  189,  189,  189,  189,  189,  150,  139,  139,
      139,  139,  139,  189,  189,  189,  189,  189,  189,  189,
      189,  189,  189,  189,  153,  189,  154,   70,   70,   70,
       70,   70,  189,  189,  189,   92,  189,  189,  189,  189,
      189,  189,  189,   93,   91,   70,   91,   91,   91,  189,

      189,  189,  157,  189,  189,  189,  189,  189,  189,  189,
      158,  161,  108,  189,  108,  162,  108,  163,  163,  163,
      163,  163,  161,  163,  163,  163,  163,  161,  164,  163,
      163,  110,  189,  110,  110,  110,  189,  189,  189,  189,
      189,  189,  189,  189,  189,  189,  189,  166,  169,  139,
      169,  169,  169,  189,  189,  189,  189,  189,  189,  189,
      189,  189,  189,  189,  170,  189,  171,  118,   70,  118,
      118,  118,  189,  189,  189,  119,  189,  189,  189,  189,
      189,  189,  189,  120,  117,   70,  117,  117,  117,  189,
      189,  189,  175,  189,  189,  189,  189,  189,  189,  189,

      176,   85,  189,   85,   85,   85,  189,  189,  189,  189,
      189,  189,  189,  189,  189,  189,  189,  150,  139,  139,
      139,  139,  139,  189,  189,  189,  189,  189,  189,  189,
      189,  189,  189,  189,  153,  189,  154,  152,  189,  152,
      152,  152,  189,  189,  189,  189,  189,  189,  189,  189,
      189,  189,  189,  180,   91,   70,   91,   91,   91,  189,
      189,  189,  157,  189,  189,  189,  189,  189,  189,  189,
      158,  110,  189,  110,  110,  110,  189,  189,  189,  189,
      189,  189,  189,  189,  189,  189,  189,  166,  169,  139,
      169,  169,  169,  189,  189,  189,  189,  189,  189,  189,

      189,  189,  189,  189,  170,  189,  171,  168,  189,  168,
      168,  168,  189,  189,  189,  189,  189,  189,  189,  189,
      189,  189,  189,  184,  117,   70,  117,  117,  117,  189,
      189,  189,  175,  189,  189,  189,  189,  189,  189,  189,
      176,  152,  139,  152,  152,  152,  189,  189,  189,  189,
      189,  189,  189,  189,  189,  189,  189,  185,  189,  186,
      168,  139,  168,  168,  168,  189,  189,  189,  189,  189,
      189,  189,  189,  189,  189,  189,  187,  189,  188,   62,
       62,   62,   62,   70,   70,   70,   70,   82,   82,  189,
       82,   85,  189,  189,   85,   91,   91,   91,   91,  109,

      109,  189,  109,  117,  117,  117,  117,  135,  135,  189,
      135,   64,   64,  189,   64,  139,  139,  139,  139,  149,
      149,  189,  149,  152,  152,  152,  152,  156,  156,  156,
      156,  165,  165,  189,  165,  168,  168,  168,  168,  118,
      118,  118,  118,  174,  174,  174,  174,  179,  179,  189,
      179,  169,  169,  169,  169,  183,  183,  189,  183,   11,
      189,  189,  189,  189,  189,  189,  189,  189,  189,  189,
      189,  189,  189,  189,  189,  189,  189,  189,  189,  189
    } ;

static const flex_int16_t yy_chk[781] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
       13,   24,   18,   13,   18,   21,   29,  191,   24,   29,
       34,   34,   34,   35,   39,   35,   21,   40,   21,   39,
       21,   21,   21,   25,   41,   46,   40,   50,   46,   50,
      186,   41,   66,   41,   25,   66,   57,   25,   95,   25,

       25,   26,   54,   57,   54,   26,   54,   95,   58,   67,
       88,   58,   26,   58,   67,   88,   88,   26,   26,   28,
       68,   84,   68,   90,   84,   90,   84,  114,  112,  138,
       28,  112,  114,   96,  138,   28,   28,   36,   36,   36,
       36,   36,   96,  118,  121,   36,  121,  139,  121,  139,
      118,  167,  128,   36,   38,  128,  167,  128,  169,  185,
      181,  160,  187,  159,  157,   38,  155,   38,  154,   38,
       38,   38,   42,  169,  185,  169,  185,  187,  149,  187,
      140,  123,  122,   42,  116,  102,   42,  100,   42,   42,
       43,   43,   99,   43,   43,   43,   43,   43,   43,   43,

       43,   43,   43,   43,   43,   43,   43,   43,   43,   43,
       45,   45,   98,   45,   45,   45,   45,   45,   45,   45,
       45,   45,   45,   45,   45,   45,   45,   45,   45,   45,
       49,   97,   92,   85,   74,   73,   70,   69,   64,   56,
       55,   49,   51,   44,   37,   33,   49,   49,   52,   52,
       52,   52,   52,   23,   22,   20,   52,   19,   12,   11,
       10,    9,    0,    0,   52,   59,   59,    0,   59,   59,
       59,   59,   59,   59,   59,   59,   59,   59,   59,   59,
       59,   59,   59,   59,   59,   65,    0,    0,    0,   65,
        0,    0,    0,    0,    0,    0,   65,    0,    0,    0,

        0,   65,   65,   83,    0,    0,    0,   83,    0,    0,
        0,    0,    0,    0,   83,    0,    0,    0,    0,   83,
       83,   86,   86,    0,   86,   86,   86,   86,   86,   86,
       86,   86,   86,   86,   86,   86,   86,   86,   86,   86,
       86,   87,    0,   87,   87,   87,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,   87,   89,   89,
       89,   89,   89,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   89,    0,   89,   91,   91,   91,
       91,   91,    0,    0,    0,   91,    0,    0,    0,    0,
        0,    0,    0,   91,   93,   93,   93,   93,   93,    0,

        0,    0,   93,    0,    0,    0,    0,    0,    0,    0,
       93,  111,  111,    0,  111,  111,  111,  111,  111,  111,
      111,  111,  111,  111,  111,  111,  111,  111,  111,  111,
      111,  113,    0,  113,  113,  113,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,  113,  115,  115,
      115,  115,  115,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,  115,    0,  115,  117,  117,  117,
      117,  117,    0,    0,    0,  117,    0,    0,    0,    0,
        0,    0,    0,  117,  120,  120,  120,  120,  120,    0,
        0,    0,  120,    0,    0,    0,    0,    0,    0,    0,

      120,  150,    0,  150,  150,  150,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,  150,  152,  152,
      152,  152,  152,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,  152,    0,  152,  153,    0,  153,
      153,  153,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,  153,  158,  158,  158,  158,  158,    0,
        0,    0,  158,    0,    0,    0,    0,    0,    0,    0,
      158,  166,    0,  166,  166,  166,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,  166,  168,  168,
      168,  168,  168,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,  168,    0,  168,  170,    0,  170,
      170,  170,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,  170,  176,  176,  176,  176,  176,    0,
        0,    0,  176,    0,    0,    0,    0,    0,    0,    0,
      176,  180,  180,  180,  180,  180,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,  180,    0,  180,
      184,  184,  184,  184,  184,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,  184,    0,  184,  190,
      190,  190,  190,  192,  192,  192,  192,  193,  193,    0,
      193,  194,    0,    0,  194,  195,  195,  195,  195,  196,

      196,    0,  196,  197,  197,  197,  197,  198,  198,    0,
      198,  199,  199,    0,  199,  200,  200,  200,  200,  201,
      201,    0,  201,  202,  202,  202,  202,  203,  203,  203,
      203,  204,  204,    0,  204,  205,  205,  205,  205,  206,
      206,  206,  206,  207,  207,  207,  207,  208,  208,    0,
      208,  209,  209,  209,  209,  210,  210,    0,  210,  189,
      189,  189,  189,  189,  189,  189,  189,  189,  189,  189,
      189,  189,  189,  189,  189,  189,  189,  189,  189,  189
    } ;

/* Table of booleans, true if rule could match eol. */
static const flex_int32_t yy_rule_can_match_eol[36] =
    {   0,
0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 
    1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "yar_lexer.l"
#line 2 "yar_lexer.l"
#include <assert.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "data_structure/string.h"
#include "yar_ast.h"
#include "yar_parser.tab.h"
#include "yar_debug.h"
#include "yar_substitution.h"
#include "yar_interpreter.h"

string __add_escape_character_all (string input);
string __add_escape_character_except (string input, const char *delim);
string __add_escape_character_except_space (string input);

int current_quoted;
int current_brace;
int arith_mode;
// int treat_brace_as_string;
void init_lexer ()
{
    current_quoted = 0;
    current_brace = 0;
    arith_mode = 0;
}

int keep_whitespace_as_string ()
{
    return current_quoted || current_brace;
}
int store_identifier_as_string ()
{
    return current_quoted || current_brace;
}
int quote_expansion ()
{
    return current_quoted || current_brace;
}
int treat_num_sign_as_string ()
{
    return current_quoted || current_brace;
}

// int yypeeklex ();

#line 760 "yar_lexer.c"

/*

"="                         { 
                                if (in_word) {
                                    int token = finish_word();
                                    unput('=');
                                    return token;
                                }
                                return EQUAL; 
                            }

"<"                         { 
                                if (in_word) {
                                    int token = finish_word();
                                    unput('<');
                                    return token;
                                }
                                return LESS; 
                            }

">"                         { 
                                if (in_word) {
                                    int token = finish_word();
                                    unput('>');
                                    return token;
                                }
                                return GREATER; 
                            }

">>"                        { 
                                if (in_word) {
                                    int token = finish_word();
                                    unput('>'); unput('>');
                                    return token;
                                }
                                return GREATER_DOUBLE; 
                            }

"<&"                        { 
                                if (in_word) {
                                    int token = finish_word();
                                    unput('&'); unput('<');
                                    return token;
                                }
                                return LESS_AND; 
                            }

">&"                        { 
                                if (in_word) {
                                    int token = finish_word();
                                    unput('&'); unput('>');
                                    return token;
                                }
                                return GREATER_AND; 
                            }

"&>"                        { 
                                if (in_word) {
                                    int token = finish_word();
                                    unput('>'); unput('&');
                                    return token;
                                }
                                return AND_GREATER; 
                            }

"&>>"                       { 
                                if (in_word) {
                                    int token = finish_word();
                                    unput('>'); unput('>'); unput('&');
                                    return token;
                                }
                                return AND_GREATER_DOUBLE; 
                            }

"<>"                        { 
                                if (in_word) {
                                    int token = finish_word();
                                    unput('>'); unput('<');
                                    return token;
                                }
                                return LESS_GREATER; 
                            }

"!"                         { 
                                if (in_word) {
                                    int token = finish_word();
                                    unput('!');
                                    return token;
                                }
                                return BANG; 
                            }

"|"                         { 
                                if (in_word) {
                                    int token = finish_word();
                                    unput('|');
                                    return token;
                                }
                                return OR; 
                            }

"&"                         { 
                                if (in_word) {
                                    int token = finish_word();
                                    unput('&');
                                    return token;
                                }
                                return AND; 
                            }

"||"                        { 
                                if (in_word) {
                                    int token = finish_word();
                                    unput('|'); unput('|');
                                    return token;
                                }
                                return OR_DOUBLE; 
                            }

"&&"                        { 
                                if (in_word) {
                                    int token = finish_word();
                                    unput('&'); unput('&');
                                    return token;
                                }
                                return AND_DOUBLE; 
                            }

"+"                         { 
                                if (in_word) {
                                    int token = finish_word();
                                    unput('+');
                                    return token;
                                }
                                return PLUS; 
                            }

"-"                         { 
                                if (in_word) {
                                    int token = finish_word();
                                    unput('-');
                                    return token;
                                }
                                return MINUS; 
                            }

"*"                         { 
                                if (in_word) {
                                    int token = finish_word();
                                    unput('*');
                                    return token;
                                }
                                return TIMES; 
                            }

"/"                         { 
                                if (in_word) {
                                    int token = finish_word();
                                    unput('/');
                                    return token;
                                }
                                return DIVIDE; 
                            }

"(("                        { 
                                if (in_word) {
                                    int token = finish_word();
                                    unput('('); unput('(');
                                    return token;
                                }
                                return ROUND_LPAREN_DOUBLE; 
                            }

"))"                        { 
                                if (in_word) {
                                    int token = finish_word();
                                    unput(')'); unput(')');
                                    return token;
                                }
                                return ROUND_RPAREN_DOUBLE; 
                            }

"[["                        { 
                                if (in_word) {
                                    int token = finish_word();
                                    unput('['); unput('[');
                                    return token;
                                }
                                return SQUARE_LPAREN_DOUBLE; 
                            }

"]]"                        { 
                                if (in_word) {
                                    int token = finish_word();
                                    unput(']'); unput(']');
                                    return token;
                                }
                                return SQUARE_RPAREN_DOUBLE; 
                            }

"("                         { 
                                if (in_word) {
                                    int token = finish_word();
                                    unput('(');
                                    return token;
                                }
                                return ROUND_LPAREN; 
                            }

")"                         { 
                                if (in_word) {
                                    int token = finish_word();
                                    unput(')');
                                    return token;
                                }
                                return ROUND_RPAREN; 
                            }

"["                         { 
                                if (in_word) {
                                    int token = finish_word();
                                    unput('[');
                                    return token;
                                }
                                return SQUARE_LPAREN; 
                            }

"]"                         { 
                                if (in_word) {
                                    int token = finish_word();
                                    unput(']');
                                    return token;
                                }
                                return SQUARE_RPAREN; 
                            }

"{"                         { 
                                if (in_word) {
                                    int token = finish_word();
                                    unput('{');
                                    return token;
                                }
                                return CURLY_LPAREN; 
                            }

"}"                         { 
                                if (in_word) {
                                    int token = finish_word();
                                    unput('}');
                                    return token;
                                }
                                return CURLY_RPAREN; 
                            }

";;"                        { 
                                if (in_word) {
                                    int token = finish_word();
                                    unput(';'); unput(';');
                                    return token;
                                }
                                return SEMICOLON_DOUBLE; 
                            }

";"                         { 
                                if (in_word) {
                                    int token = finish_word();
                                    unput(';');
                                    return token;
                                }
                                return SEMICOLON; 
                            }

"if"                        { 
                                if (in_word) {
                                    add_to_word(yytext);
                                } else {
                                    return IF;
                                }
                            }

"then"                      { 
                                if (in_word) {
                                    add_to_word(yytext);
                                } else {
                                    return THEN;
                                }
                            }

"elif"                      { 
                                if (in_word) {
                                    add_to_word(yytext);
                                } else {
                                    return ELIF;
                                }
                            }

"else"                      { 
                                if (in_word) {
                                    add_to_word(yytext);
                                } else {
                                    return ELSE;
                                }
                            }

"fi"                        { 
                                if (in_word) {
                                    add_to_word(yytext);
                                } else {
                                    return FI;
                                }
                            }

"for"                       { 
                                if (in_word) {
                                    add_to_word(yytext);
                                } else {
                                    return FOR;
                                }
                            }

"in"                        { 
                                if (in_word) {
                                    add_to_word(yytext);
                                } else {
                                    return IN;
                                }
                            }

"do"                        { 
                                if (in_word) {
                                    add_to_word(yytext);
                                } else {
                                    return DO;
                                }
                            }

"done"                      { 
                                if (in_word) {
                                    add_to_word(yytext);
                                } else {
                                    return DONE;
                                }
                            }

"while"                     { 
                                return WHILE;
                            }

"until"                     { 
                                return UNTIL;
                            }

"case"                      { 
                                return CASE;
                            }

"esac"                      { 
                                return ESAC;
                            }

"break"                     { 
                                return BREAK;
                            }

"continue"                  { 
                                return CONTINUE;
                            }

"return"                    { 
                                return RETURN;
                            }

"exit"                      { 
                                return EXIT;
                            }

"exec"                      { 
                                return EXEC;
                            }

"trap"                      { 
                                return TRAP;
                            }

"time"                      { 
                                return TIME;
                            }

"coproc"                    { 
                            }
*/
#line 1153 "yar_lexer.c"

#define INITIAL 0
#define DOUBLE_QUOTE_STRING 1
#define SINGLE_QUOTE_STRING 2
#define BRACE_STRING 3
#define COMMENT 4

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

YYSTYPE * yyget_lval ( void );

void yyset_lval ( YYSTYPE * yylval_param  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

        static int yy_start_stack_ptr = 0;
        static int yy_start_stack_depth = 0;
        static int *yy_start_stack = NULL;
    
    static void yy_push_state ( int _new_state );
    
    static void yy_pop_state ( void );
    
    static int yy_top_state ( void );
    
/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex \
               (YYSTYPE * yylval_param );

#define YY_DECL int yylex \
               (YYSTYPE * yylval_param )
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
        YYSTYPE * yylval;
    
    yylval = yylval_param;

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 461 "yar_lexer.l"


#line 1397 "yar_lexer.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 190 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_current_state != 189 );
		yy_cp = (yy_last_accepting_cpos);
		yy_current_state = (yy_last_accepting_state);

yy_find_action:
		yy_act = yy_accept[yy_current_state];

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 463 "yar_lexer.l"
{
                            DEBUG_PRINT("debug: flex catch variable substitution: `%s`\n", yytext);
                            string content = variable_substitution_handler(yytext);
                            if (quote_expansion ())
                            {
                                yylval->str_frag = make_string_fragment (STR_FRAG_QUOTED, content);
                            }
                            else {
                                content = __add_escape_character_except_space (content);
                                yylval->str_frag = make_string_fragment (STR_FRAG_NON_QUOTED, content);
                            }
                            return STRING;
                        }
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 477 "yar_lexer.l"
{
                            DEBUG_PRINT("debug: flex catch string substitution: `%s`\n", yytext);
                            string content = string_substitution_handler(yytext);
                            fprintf (stderr, "content debug: %s\n", content);
                            if (quote_expansion ())
                            {
                                yylval->str_frag = make_string_fragment (STR_FRAG_QUOTED, content);
                            }
                            else {
                                content = __add_escape_character_except_space (content);
                                yylval->str_frag = make_string_fragment (STR_FRAG_NON_QUOTED, content);
                            }
                            fprintf (stderr, "content debug: %s\n", content);
                            return STRING;
                        }
	YY_BREAK

case 3:
YY_RULE_SETUP
#line 494 "yar_lexer.l"
{
                            yylval->str_frag = make_string_fragment (STR_FRAG_QUOTED,
                                                                    new_string_2 (yytext));
                            return STRING;
                        }
	YY_BREAK
case 4:
/* rule 4 can match eol */
YY_RULE_SETUP
#line 499 "yar_lexer.l"
{
                            ++yylineno;
                            yylval->str_frag = make_string_fragment (STR_FRAG_QUOTED,
                                                                    new_string_2 (yytext));
                            return STRING;
                        }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 505 "yar_lexer.l"
{
                            current_quoted = 0;
                            yy_pop_state ();
                            return DOUBLE_QUOTE;
                        }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 510 "yar_lexer.l"
{
                            DEBUG_ASSERT (strlen(yytext) == 1);
                            if (yytext[0] == '\n')
                            {
                                ++yylineno;
                            }
                            string content = new_string_2 (yytext);
                            yylval->str_frag = make_string_fragment(STR_FRAG_QUOTED, content);
                            return STRING;
                        }
	YY_BREAK

case 7:
YY_RULE_SETUP
#line 521 "yar_lexer.l"
{
                            current_quoted = 1;
                            yy_push_state (DOUBLE_QUOTE_STRING);
                            string_list *list = interpret_string (TOK_NIL, SIM_STR_INT_DOUBLE_QUOTE);
                            DEBUG_ASSERT (list && list->next == NULL);
                            string content = new_string_2 (list->str);
                            content = __add_escape_character_all (content);
                            yylval->str_frag = make_string_fragment (STR_FRAG_QUOTED, content);
                            free_string_list (list);
                            return STRING;
                        }
	YY_BREAK

case 8:
YY_RULE_SETUP
#line 534 "yar_lexer.l"
{
                            current_brace = 0;
                            yy_pop_state ();
                            return BRACE_RIGHT;
                        }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 539 "yar_lexer.l"
{
                            yylval->str_frag = make_string_fragment (STR_FRAG_QUOTED,
                                                                    new_string_2 (yytext));
                            return STRING;
                        }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 544 "yar_lexer.l"
{
                            string content = new_string_2 (yytext);
                            yylval->str_frag = make_string_fragment(STR_FRAG_QUOTED, content);
                            return STRING;
                        }
	YY_BREAK

case 11:
YY_RULE_SETUP
#line 550 "yar_lexer.l"
{
                            current_brace = 1;
                            yy_push_state (BRACE_STRING);
                            string_list *list = interpret_string (TOK_NIL, SIM_STR_INT_BRACE);
                            DEBUG_ASSERT (list && list->next == NULL);
                            string content = new_string_2 ("\{");
                            content = string_append_back (content, list->str);
                            yylval->str_frag = make_string_fragment (STR_FRAG_QUOTED, content);
                            free_string_list (list);
                            return STRING;
                        }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 562 "yar_lexer.l"
{
    if (keep_whitespace_as_string ())
    {
        string content = new_string_2 (yytext);
        yylval->str_frag = make_string_fragment (STR_FRAG_QUOTED,
                                                content);
        return STRING;
    }
    return WHITESPACE;
}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 573 "yar_lexer.l"
{
    if (store_identifier_as_string ())
    {
        string content = new_string_2 (yytext);
        yylval->str_frag = make_string_fragment (STR_FRAG_QUOTED,
                                                content);
        return STRING;
    }
    yylval->str = new_string_2(yytext);
    return IDENTIFIER_ASSIGNMENT;
}
	YY_BREAK

case 14:
/* rule 14 can match eol */
YY_RULE_SETUP
#line 586 "yar_lexer.l"
{
                            // skip all the   # ..... \n
                            // return newline token as the comment should not be exist
                            yy_pop_state ();
                            return NEWLINE;
                        }
	YY_BREAK
case YY_STATE_EOF(COMMENT):
#line 592 "yar_lexer.l"
{
                            // skip all the   # ..... <<EOF>>
                            // return newline token as the comment should not be exist
                            yy_pop_state ();
                            return NEWLINE;
                        }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 598 "yar_lexer.l"
;
	YY_BREAK

case 16:
YY_RULE_SETUP
#line 600 "yar_lexer.l"
{
                            if (treat_num_sign_as_string ())
                            {
                                string content = new_string_2 (yytext);
                                yylval->str_frag = make_string_fragment (STR_FRAG_QUOTED, content);
                                return STRING;
                            }
                            else {
                                // enter comment state
                                yy_push_state (COMMENT);
                            }
                        }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 613 "yar_lexer.l"
{
                            DEBUG_ASSERT (strlen(yytext) == 2);
                            string content = new_string_2 (yytext + 1);
                            yylval->str_frag = make_string_fragment (STR_FRAG_QUOTED, content);
                            return STRING;
                        }
	YY_BREAK
case 18:
/* rule 18 can match eol */
YY_RULE_SETUP
#line 620 "yar_lexer.l"
{
                            string content = new_substr (yytext + 1, yytext + strlen(yytext) - 1);
                            content = __add_escape_character_all (content);
                            yylval->str_frag = make_string_fragment(STR_FRAG_QUOTED, content);
                            return STRING;
                        }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 626 "yar_lexer.l"
{
                                    yylval->str_frag = make_string_fragment(STR_FRAG_QUOTED,
                                                            new_string_2(yytext) );
                                    return STRING;
                                }
	YY_BREAK
case 20:
/* rule 20 can match eol */
YY_RULE_SETUP
#line 632 "yar_lexer.l"
{
    ++yylineno;
    return NEWLINE;
}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 636 "yar_lexer.l"
{
    return SEMICOLON;
}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 639 "yar_lexer.l"
{
    return SEMICOLON_DOUBLE;
}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 643 "yar_lexer.l"
{
    return LESS;
}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 646 "yar_lexer.l"
{
    return NUM_LESS;
}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 649 "yar_lexer.l"
{
    return GREATER;
}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 652 "yar_lexer.l"
{
    return NUM_GREATER;
}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 655 "yar_lexer.l"
{
    return GREATER_DOUBLE;
}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 658 "yar_lexer.l"
{
    return AND_GREATER;
}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 661 "yar_lexer.l"
{
    return GREATER_AND;
}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 664 "yar_lexer.l"
{
    return AND_GREATER_DOUBLE;
}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 667 "yar_lexer.l"
{
    return LESS_AND;
}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 670 "yar_lexer.l"
{
    return NUM_LESS_AND;
}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 673 "yar_lexer.l"
{
    return NUM_GREATER_AND;
}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 677 "yar_lexer.l"
{
                            fprintf (stderr, "Unexpected character: %c\n", yytext[0]);
                        }
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(DOUBLE_QUOTE_STRING):
case YY_STATE_EOF(SINGLE_QUOTE_STRING):
case YY_STATE_EOF(BRACE_STRING):
#line 680 "yar_lexer.l"
{
                            return 0;
                        }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 684 "yar_lexer.l"
ECHO;
	YY_BREAK
#line 1824 "yar_lexer.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_last_accepting_cpos);
				yy_current_state = (yy_last_accepting_state);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 190 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 190 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 189);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

    static void yy_push_state (int  _new_state )
{
    	if ( (yy_start_stack_ptr) >= (yy_start_stack_depth) )
		{
		yy_size_t new_size;

		(yy_start_stack_depth) += YY_START_STACK_INCR;
		new_size = (yy_size_t) (yy_start_stack_depth) * sizeof( int );

		if ( ! (yy_start_stack) )
			(yy_start_stack) = (int *) yyalloc( new_size  );

		else
			(yy_start_stack) = (int *) yyrealloc(
					(void *) (yy_start_stack), new_size  );

		if ( ! (yy_start_stack) )
			YY_FATAL_ERROR( "out of memory expanding start-condition stack" );
		}

	(yy_start_stack)[(yy_start_stack_ptr)++] = YY_START;

	BEGIN(_new_state);
}

    static void yy_pop_state  (void)
{
    	if ( --(yy_start_stack_ptr) < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN((yy_start_stack)[(yy_start_stack_ptr)]);
}

    static int yy_top_state  (void)
{
    	return (yy_start_stack)[(yy_start_stack_ptr) - 1];
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

    (yy_start_stack_ptr) = 0;
    (yy_start_stack_depth) = 0;
    (yy_start_stack) =  NULL;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Destroy the start condition stack. */
        yyfree( (yy_start_stack)  );
        (yy_start_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 684 "yar_lexer.l"


string __add_escape_character_all (string input)
{
    string res = new_string ();
    size_t len = string_length (input);
    for (size_t i = 0; i < len; ++i)
    {
        res = string_push_back (res, '\\');
        if (input[i] == '\\')
        {
            ++i;
        }
        if (i < len) {
            res = string_push_back (res, input[i]);
        }
    }
    free_string (input);
    return res;
}
string __add_escape_character_except (string input, const char *delim)
{
    string res = new_string ();
    size_t len = string_length (input);
    for (size_t i = 0; i < len; ++i)
    {
        if (strchr (delim, input[i])) {
            res = string_push_back (res, input[i]);
            continue;
        }
        res = string_push_back (res, '\\');
        if (input[i] == '\\')
        {
            ++i;
        }
        if (i < len) {
            res = string_push_back (res, input[i]);
        }
    }
    free_string (input);
    return res;
}

string __add_escape_character_except_space (string input)
{
    return __add_escape_character_except (input, " \t\r");
}

// void free_metadata (int token, YYSTYPE *val)
// {
//     switch (token)
//     {
//         case STRING:
//             free (val->str_frag.value);
//             break;
//         case IDENTIFIER_ASSIGNMENT:
//             free_string (val->str);
//             break;
//         default:
//             break;
//     }
// }
//
// int yypeeklex ()
// {
//     YYSTYPE tmp;
//     int token = yylex (&tmp);
//     free_metadata (token, &tmp);
//     for (size_t i = strlen (yytext); i-- > 0; )
//         unput (yytext[i]);
//     return token;
// }

